### PR TITLE
few more string functions

### PR DESCRIPTION
**Pull request by tamimibrahim17**
More to come 👍

### CODE REVIEW

**Comment by sohelamin** [comment]
Wow that's great (y)
You don't need to run the build command I will do it myself. Just follow the contribution guide https://github.com/appzcoder/30-seconds-of-php-code/blob/master/CONTRIBUTING.md

**Comment by sohelamin** [comment]
And please don't update the composer.json file

**Comment by tamimibrahim17** [comment]
OK! @sohelamin vhai, 

However, I have read contribution guide and tried my best as per rules. :) Can you please tell me what did I missed ? 

Thanks

**Comment by sohelamin** [comment]
Well, I can see you ran the build command and change phpunit on composer.json file
And you need to make sure the PS2 coding style.
eg. 4 spaces instead of tab, space between arguments, identical operator, bla bla.
```php
function isAnagram($str1, $str2)
{
    return count_chars($str1, 1) === count_chars($str2, 1);
}

isAnagram('looped', 'poodle');
```

Or leave the formatting I will reformat it myself then you can check it later.

**Pull request merged**
