### PR TITLE
including bubbleSort function

### PR DESCRIPTION
**Pull request by enkaypeter**
Including a function `bubbleSort()` to perform  bubble sort.

### CODE REVIEW

**Comment by sohelamin** [comment]
@enkaypeter Since, the repo is supposed to make snippet within 30 seconds, please make the snippet shorter as possible.

**Comment by enkaypeter** [comment]
Alright, i'll refactor and push

**Comment by enkaypeter** [comment]
Done

**Comment by peter279k** [comment]
The `database.json` is conflict, please fix this.

**Pull request merged**
